apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: buildkite-agent
  namespace: external-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buildkite-agent
  minReplicas: 1
  maxReplicas: 40
  metrics:
    - type: External
      external:
        metric:
          name: buildkite_busy_agent_percentage
        target:
          type: Value
          value: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 25
          periodSeconds: 600
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
