name: Linting

on:
  push:
    branches: *
  pull_request:
    branches: *

permissions:
  contents: read

jobs:

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
